CrocSwap/perps-app

- app/contexts/TradingviewContext.tsx
**Steps to reproduce the bug**
1. open the chart
2. Update any property stored in local storage (add new indicator, switch interval etc.)
3. open another page
4. return to the trade page
**Fix Details**
- default volume indicator is no longer added if a saved instance exists in local storage
> fixed : multiple volume display when switching pages

- app/components/Trade/OrderInput/OrderInput.tsx
- app/components/Trade/OrderInput/PlaceOrderButtons/PlaceOrderButtons.tsx
- app/components/Trade/OrderInput/SizeInput/SizeInput.tsx
- app/routes/trade/orderbook/orderbook.tsx
- app/routes/trade/orderbook/orderrow/orderrow.module.css
- app/routes/trade/orderbook/orderrow/orderrow.tsx
- app/stores/TradeDataStore.ts
New orderbook click handlers has been added
- Click by field (price, size, total)
- Store values has been added into TradeDataStore (`obChosenPrice`, `obChosenAmount`)
- Lock orderbook 1sec after clicking to make clear which row has been clicked
- Assign clicked values into Trade Module
- Change Trade Module `Order Type` if needed
Order Type change rules;
- Market -> Limit
- Stop Market -> Stop Limit
Copy Rules;
- Price click -> (Copy price into price input)
- Size & Total amount click (copy both price and amount into size and price inputs)
For the size, sum of orders until selected order type (buy/sell) has been copied into size input (which means total size)
> Orderbook | New click handler to copy slot values into Trade Module

- packages/frontend/app/components/Trade/OrderHistoryTable/OrderHistoryTable.tsx
- packages/sdk/src/utils/types.ts
- packages/sdk/src/ws.ts
UserOrderHistory channel-related types have been added to the SDK to fix the issue that was triggered when switching the Trades tab.
> SDK | User order history

- packages/frontend/app/routes/chart/orders/component/LineComponent.ts
- packages/frontend/app/routes/chart/orders/customOrderLineUtils.ts
- packages/frontend/app/routes/chart/orders/openOrderLine.tsx
Fixes :
- Drawn shapes cant be drag
1. Switch to Crazy Account
2. Draw any shape using the drawing tool
3. Try dragging the shape  
- Missing limit order lines for Benjamin Hyper account
İmprovment  :
- Quantity text width increased
> Fix shape dragging issue on chart

- packages/frontend/app/routes/chart/orders/component/LineComponent.ts
Fixes :
- black screen occur after DOGE, DXDY or ATOM coins open
- kPepe coin limit order lines not display
> Fix black screen when opening DOGE, DXDY or ATOM coins

- packages/frontend/app/routes/trade/orderbook/orderbook.module.css
- packages/frontend/app/routes/trade/orderbook/orderbook.tsx
- packages/frontend/app/routes/trade/orderbook/orderrow/orderrow.tsx
Transition has been added for OrderRows in OrderBook
Ratio component has been moved into wrapper component to not effect by re-render once related row has been updated
Div hierarchy has been changed in OrderBook, and transition has been added into ratio div
> OrderBook | Order row ratio transitions

- packages/frontend/app/components/Pagination/Pagination.module.css
- packages/frontend/app/components/Pagination/Pagination.tsx
- packages/frontend/app/components/Trade/OpenOrdersTable/OpenOrdersTable.tsx
- packages/frontend/app/components/Trade/PositionsTable/PositionsTable.module.css
- packages/frontend/app/components/Trade/PositionsTable/PositionsTable.tsx
- packages/frontend/app/root.tsx
- packages/frontend/app/routes.ts
- packages/frontend/app/routes/positions/positions.module.css
- packages/frontend/app/routes/positions/positions.tsx
- packages/frontend/app/routes/trade.tsx
Limiting positions data on positions table to 10 (in Trade Page)
- View all button has been added to show all positions in another page
- Pagination component for using in PositionsTable component
- Positions Table has been modified to use both Trade Tables and Positions Page
- `Positions.tsx` component to render table in `/positions` route
> Positions Table | View all button to open positions in a separate page

- packages/frontend/app/components/Tabs/Tabs.tsx
- packages/frontend/app/components/Trade/TradeTables/TradeTables.tsx
- packages/frontend/app/hooks/usePage.ts
`Funding History` and `Deposits and Withdrawals` tabs are hidden on Trade Page
Changes;
- usePage hook has been created to track current page (trade and portfolio types have been added for now)
- Using page hook on TradeTables component to hide tabs on Trade Page
- Fix on Tabs component to select 'Balances' tab if last selected tab is not rendered in Trade Page (needed to add a useEffect to Tabs component)
> Trade Tables | Hiding some tabs on Trade Page

- packages/frontend/app/contexts/TradingviewContext.tsx
The issue occurs on the first load in an private chrome tab or during the initial deployment
> fix: chart loading screen color is grey on first deploy

- packages/frontend/app/components/Tables/GenericTable/GenericTable.tsx
- packages/frontend/app/components/Tabs/Tabs.tsx
- packages/frontend/app/components/Trade/BalancesTable/BalancesTable.module.css
- packages/frontend/app/components/Trade/BalancesTable/BalancesTable.tsx
- packages/frontend/app/components/Trade/BalancesTable/BalancesTableHeader.tsx
- packages/frontend/app/components/Trade/FundingHistoryTable/FundingHistoryTable.module.css
- packages/frontend/app/components/Trade/OpenOrdersTable/OpenOrdersTable.module.css
- packages/frontend/app/components/Trade/OrderHistoryTable/OrderHistoryTable.module.css
- packages/frontend/app/components/Trade/PositionsTable/PositionsTable.module.css
- packages/frontend/app/components/Trade/TradeHistoryTable/TradeHistoryTable.module.css
- packages/frontend/app/components/Trade/TradeTables/TradeTables.tsx
- packages/frontend/app/components/Trade/TwapTable/FillTwapTable/FillTwapTable.module.css
- packages/frontend/app/components/Trade/TwapTable/FillTwapTable/FillTwapTable.tsx
- packages/frontend/app/components/Trade/TwapTable/HistoryTwapTable/HistoryTwapTable.module.css
- packages/frontend/app/components/Trade/TwapTable/HistoryTwapTable/HistoryTwapTable.tsx
- packages/frontend/app/components/Trade/TwapTable/TwapTable.tsx
- packages/frontend/app/css/index.css
- packages/frontend/app/routes/twapHistory/twapHistory.tsx
Tab height incosistency fixed once tab has been changed.
- Static height (optional) has been added into Tab Component
- Trade tabs height has been added into index.css
- Height override has been added into Generic Table (to fix Twap tables)
- Generic table has been used on Balances table
- Redundant css classes has been removed from table component css modules
> Trade Tab & Tabel fixes

- packages/frontend/app/routes/trade/symbol/symbolinfo.tsx
- packages/frontend/app/routes/trade/symbol/symbolinfofield/symbolinfofield.module.css
- packages/frontend/app/routes/trade/symbol/symbolinfofield/symbolinfofield.tsx
- packages/frontend/app/routes/trade/symbol/symbolsearch/symbolsearch.module.css
- packages/frontend/app/routes/trade/watchlist/watchlist.module.css
- packages/frontend/app/routes/trade/watchlist/watchlistnode/watchlistnode.module.css
- Watchlist has too much left padding
- Hover state for watched markets should be dark3, looks like dark4
- Market info area has too much left padding
- Add a hoverstate to the market select area - refer figma
- Need a hover state and tooltip for things in the market details like oracle price etc
- Can the “dollars/percent” buttons also have an area around it for the hover state - refer figma
-
> complete frontend review for watchlist and market info

- packages/frontend/app/routes/trade/orderbook/orderbooksection.module.css
- packages/frontend/app/routes/trade/symbol/symbolsearch/symbollist/SymbolListTableRow.tsx
- packages/frontend/app/routes/trade/symbol/symbolsearch/symbollist/symbollist.module.css
fix menu dot alignment
SEARCH BOX - i would like to line up the search box with the top and left of the chart. This way the search will line up with the market button above 
SEARCH BOX - search field border radius should be 8
SEARCH BOX - reduce the height of the leverage pill. It should be smaller than the row height. In figma i have a row height of 17, a leverage pill height of 15, left padding of 4, and right padding of 8, and a gap between rows of 4
SEARCH BOX - add border radius to the rows - 4px
SEARCH BOX - we can remove the spaces from the market names eg. BTC-USD
> Search box frontend review

- packages/frontend/app/contexts/TradingviewContext.tsx
**Functionalities or workflows that should specifically be tested:**
1. Open the trade page in one browser tab (https://.../trade/BTC)
2. Open the same trade page in a new browser tab 
3. In one of the new tabs, change the selected pool (https://.../trade/DOGE)
4. Go back to the original tab and refresh the page
5. Verify that the original tab shows the pool based on its own URL
**Previously:** Refreshing a tab after changing the pool in another tab would show the other tab's selected pool in the chart
**Now expected:** Each tab should display the pool according to its own URL, even after a page refresh.
> Wrong market showing on chart when refresh page

- packages/frontend/app/hooks/useSdk.tsx
- packages/sdk/src/websocket-instance.ts
- packages/sdk/src/websocket-pool.ts
Reconnect issue has been fixed for multi socket approach.
_Problem is being triggered after 30m timeout which stops active sockets._
Stashing active subs and reInit action for active sockets has been implemented
> Websocket | Fix Reconnect Issue for MultiSocketInfo

- packages/frontend/app/components/Trade/OrderInput/MarginModal/MarginModal.module.css
- packages/frontend/app/components/Trade/OrderInput/MarginModal/MarginModal.tsx
- packages/frontend/app/components/Trade/OrderInput/OrderInput.tsx
Remove the CTA button in the Margin Mode modal. Clicking one of the two options will directly set state. The modal must be dismissed as a second user action (outside click, `X` click, <kbd>Esc</kbd> keypress).
> remove margin modal CTA

- packages/frontend/app/components/Trade/OrderInput/LeverageSlider/LeverageSlider.tsx
- packages/frontend/app/components/Trade/OrderInput/PositionSIze/PositionSize.tsx
1. Fixed Click-and-Drag Interaction Bug
Issue:
When users clicked on the slider track and then attempted to drag, the slider would not respond during the drag but would only update when the mouse was released.
Cause: 
The track used onClick event, which only set isDragging = false after you are finished. Anything else was ignored because the  state was never activated.
Fix:
Replaced onClick with onMouseDown on slider track
Added handleTrackMouseDown and handleTrackTouchStart functions that handles the initial clicking and dragging
2. Fixed Memory Leak in Drag Event Listeners
Issue:
The drag handling useEffect hasd the  currentValue in its dependency array, causing the effect to re-run on every value change during dragging.
Fix:
Added currentValueRef to track the current value via ref …
> improve sliders interactions

- packages/frontend/app/components/PageHeader/DropdownMenu/DropdownMenu.tsx
- packages/frontend/app/components/PageHeader/PageHeader.tsx
- packages/frontend/app/components/Portfolio/PortfolioDeposit/PortfolioDeposit.tsx
- packages/frontend/app/components/Portfolio/PortfolioSend/PortfolioSend.tsx
- packages/frontend/app/components/Portfolio/PortfolioWithdraw/PortfolioWithdraw.tsx
- packages/frontend/app/components/Tooltip/Tooltip.module.css
- packages/frontend/app/components/Trade/LeverageSliderModal/LeverageSliderModal.tsx
- packages/frontend/app/components/Trade/OrderInput/ChaseDistance/ChaseDistance.tsx
- packages/frontend/app/components/Trade/OrderInput/ConfirmationModal/ConfirmationModal.tsx
- packages/frontend/app/components/Trade/OrderInput/OrderDetails/OrderDetails.tsx
- packages/frontend/app/components/Trade/OrderInput/OrderInput.tsx
- packages/frontend/app/components/Trade/OrderInput/ReduceAndProfitToggle/ReduceAndProfitToggle.tsx
- packages/frontend/app/components/Trade/OrderInput/ScaleOrders/DistributionDropdown.tsx
- packages/frontend/app/components/Vault/DepositModal/DepositModal.tsx
- packages/frontend/app/components/Vault/WithdrawModal/WithdrawModal.tsx
- packages/frontend/app/css/index.css
- packages/frontend/app/routes/trade/symbol/symbolinfofield/symbolinfofield.tsx
Certain svgs seem blurry and less sharp on smaller screens. The highest quality in svg library is Lucide.
All tooltip icon svgs should now be using the lucid versions.
> Change all tooltips svgs to lucid svgs

- packages/frontend/app/hooks/useSdk.tsx
- packages/sdk/src/websocket-instance.ts
Backdoor has been added into websocket-instance to get channel name without parsing message to check if a message is required for updating user data.
That mechanism is working on sleep mode,
Allowed channels;
- userFills ( Trade history)
- userHistoricalOrders (Order History)
- webData2 (Open Orders and Positions)
- _userTwapSliceFills (Twap data no need for now)_
- _userTwapHistory (Twap data no need for now)_
That channels can be managed in code (line: 31)
`websocket-instance.ts`
`const WsBackdoorChannelsForSleepMode = new Set([
'userFills',
'userHistoricalOrders',
'userTwapSliceFills',
'userTwapHistory',
'webData2',
]);
`
Also preventing user channels from stashing has been reverted, because we are using that stash mechanism to open subscriptions again if ws connection is dropped (so …
> Websocket | Backdoor for User based channels

- packages/frontend/app/routes/chart/orders/component/LabelComponent.ts
- packages/frontend/app/routes/chart/orders/component/LineComponent.ts
- packages/frontend/app/routes/chart/orders/useOpenOrderLines.ts
While dragging to update an open limit order in a different theme, the new order is sent with the wrong side (e.g., buy instead of sell), causing the order to be executed immediately
> fix: order side was incorrect when repositioned in a different theme

- packages/frontend/app/routes/chart/orders/component/LabelComponent.ts
Limit Order Line stays at dragged price even if reposition fails
> fix: revert order line if reposition fails on drag

- packages/frontend/app/components/Trade/MarketCloseModal/MarketCloseModal.tsx
- packages/frontend/package.json
- add fallback on markPx from pyth for market closes when orderbook not available
> Release 0.1.23

- packages/frontend/app/hooks/workers/orderbook.worker.ts
- packages/frontend/app/routes/trade/orderbook/orderbook.tsx
- packages/frontend/app/routes/trade/orderbook/orderbooksection.tsx
- packages/frontend/app/routes/trade/orderbook/orderbooktrades.tsx
- packages/sdk/src/websocket-instance.ts
L2Book subscription has been re-enabled for Orderbook. Also, redundant prop drilling has been fixed in OrderBook components (both Book and Trades) - the symbol is now fetched directly from the zustand store
> OrderBook | Websocket Subscription

- packages/frontend/app/components/Modal/Modal.tsx
Prevent modals from closing when releasing a drag outside the modal.
Previously, any mouse/touch release outside the modal was treated as a backdrop click, which caused accidental dismissals, especially with the slider. Now the modal only closes if the interaction starts and ends on the backdrop.
> rework handle outside click to fix accidental closing of the modal

- packages/frontend/app/routes/trade/orderbook/orderbooksection.module.css
Hiding scrollbars for stacked and large mode once layout height has been changed
> OrderBook | Hide scrollbars for Stacked and Large Mode

- packages/frontend/app/routes/trade/orderbook/orderbook.tsx
Showing spread text as gap between first sell and last buy slots, showing empty for loading state
> Orderbook | Fix spread text
