CrocSwap/perps-app

app/routes.ts, app/routes/testpage/testpage.module.css, app/routes/testpage/testpage.tsx
Create a new test page to sandbox new feature development.
Data is located in the `/route/testpage` directory.
Page renders at the `/testpage` URL route.
=> create test page

.gitignore, .prettierrc, app/routes.ts, app/routes/trade.tsx
to support routes like /trade/eth or /trade/btc
=> add marketId dynamic segment to trade route

app/components/Vault/SortIcon.tsx, app/components/Vault/VaultRow/SnapshotGraph.tsx, app/components/Vault/VaultRow/VaultRow.module.css, app/components/Vault/VaultRow/VaultRow.tsx, app/components/Vault/VaultRowHeader/VaultRowHeader.tsx, app/components/Vault/VaultTimeframe/VaultTimeframe.module.css, app/components/Vault/VaultTimeframe/VaultTimeframe.tsx, app/css/app.css, app/css/index.css, app/root.tsx, app/routes/vaults/data.ts, app/routes/vaults/vaults.module.css, app/routes/vaults/vaults.tsx
=> Build vaults page layout

app/components/BasicMenu/BasicMenu.tsx, app/components/Inputs/ComboBox/ComboBox.tsx
useOutsideClick hook has been used both Combobox and BasicMenu components
=> Outside click listeners for ComboBox and BasicMenu components

app/contexts/TradingviewContext.tsx, app/root.tsx
**workflows for test**
1. Enable log scale on main chart
2. Refresh page
=> Fixed: broken volume scale

app/routes/trade.module.css, app/routes/trade/trademodules/trademodules.tsx, app/utils/Constants.ts
Add Crazy2 account for debugging, remove content of TradesModule (user orders)
=> Add Crazy2 account for debugging, remove content of TradesModule (user orders)

app/components/Notifications/Notifications.module.css, app/components/Notifications/Notifications.tsx, app/root.tsx, app/routes/trade.tsx, app/stores/NotificationStore.ts
Subscribe notification channel on Hyperliquid services to feed notifications store with Websocket data
Changes:
- WebSocket context moved into App component
- z-index rule has been changed to render notifications properly on Trade.tsx
- Subscription and handler added into Notifications.tsx component
- Add method for websocket data has been added into NotificationStore.ts
=> Subscribe notification channel on Hyperliquid services

app/components/Wrappers/HorizontanScrollable/HorizontalScrollable.module.css, app/components/Wrappers/HorizontanScrollable/HorizontalScrollable.tsx, app/routes/trade/symbol/symbolinfo.module.css, app/routes/trade/symbol/symbolinfo.tsx, app/routes/trade/watchlist/watchlist.module.css, app/routes/trade/watchlist/watchlist.tsx
Horizontal scrollable component generated and adapted into SymbolInfo and WatchList components
=> Horizontal scroll for Symbol Info and WatchList components

app/components/Trade/PositionsTable/PositionsTable.tsx, app/components/Trade/PositionsTable/PositionsTableRow.tsx
Positions table data has been added into related table
=> Positions table

app/components/Core/RuntimeDomManipulation.tsx, app/root.tsx, app/routes/trade/orderbook/orderbook.tsx, app/routes/trade/symbol/symbolsearch/symbollist/SymbolListTableRow.tsx, app/routes/trade/symbol/symbolsearch/symbollist/symbollist.module.css, app/routes/trade/symbol/symbolsearch/symbollist/symbollist.tsx, app/routes/trade/symbol/symbolsearch/symbolsearch.tsx, app/routes/trade/traderoutehandler.tsx, app/utils/orderbook/OrderBookUtils.ts
- Showing fav symbols on top of list while sorting
- X icon has been added to clear input box (Symbol search)
- Escape key listener has been added into input box (Symbol search)
- `k{SYMBOL}` pattern coin issues fixed for both image and page rendering
- Resolution list for orderbook handled for low valued coins (HMSTR etc)
- Disable spellchecking for inputs by default (to enable `spellcheck-enabled` class should be added into related elements)
=> Symbol search changes

app/css/index.css, app/routes/trade.module.css, app/routes/trade.tsx
Fixing unexpected scrollbar rendering once resize page
- Added css variables (Trade tables height, Header height)
- Modify upper trio panel max-heights relatively to that static components
=> Unexpected scrollbar issue

app/components/Wrappers/HorizontanScrollable/HorizontalScrollable.module.css, app/routes/trade/symbol/symbolsearch/symbollist/symbollist.tsx, app/routes/trade/watchlist/watchlistnode/watchlistnode.module.css
- Rendering x icon conditionally
- Closing SymbolSearch panel when input is empty
- Fix watchlist node price text alignment
=> Symbolsearch input fixes

app/routes/trade/symbol/symbolsearch/symbollist/symbollist.module.css, app/routes/trade/symbol/symbolsearch/symbollist/symbollist.tsx
Empty state handled on symbol list
=> Symbol List | Empty state

app/components/Trade/OrderInput/OrderInput.tsx, app/components/Trade/OrderInput/PlaceOrderButtons/PlaceOrderButtons.tsx, app/hooks/useNumFormatter.ts
For a selected slot and order type (market or limit)
Required fields are being calculated and updated on trade module
=> Orderbook -> Trade Module | Binding 'Order Value & Margin Required' Fields

app/routes/trade/orderbook/orderrow/orderrow.module.css
All texts for user slots changed into yellow
=> OrderBook | User order slot coloring

app/components/Trade/PositionsTable/PositionsTableRow.tsx, app/processors/workers/webdata2.worker.ts, app/routes/trade/webdataconsumer.tsx, app/stores/TradeDataStore.ts, app/utils/position/PositionIFs.ts
- `webdata2.worker` file has been updated to process tp sl values for active positions
- Positions table has been updated with that filled values
- Map<Coin,Price> has been added into TradeDataStore to not filter coins list on each update
- Processor for coin price map has been added into `webdata2.worker` file
=> Positions Table | Adding TP/SL field from open orders

packages/frontend/app/components/Trade/OrderHistoryTable/OrderHistoryTableRow.tsx, packages/frontend/app/components/Trade/OrderInput/OrderInput.tsx
- Order History table integrated with currency mode
- Size assignemnt which triggered once orderbook slot click has been commented out
=> Order History currency mode, Trade module click rule change

packages/frontend/app/components/Tabs/Tabs.tsx
add counts for active balances/positions/orders to trade table labels
=> add count to trade table labels

packages/frontend/app/components/Trade/TradeTables/TradeTables.tsx, packages/frontend/app/stores/TradeDataStore.ts
re-initialize the app on whatever trade tab the user last had open, except re-initialize on Positions if Balances was open.
=> add trade tab persistence

packages/frontend/app/components/Skeletons/NoDataRow.module.css, packages/frontend/app/components/Skeletons/NoDataRow.tsx, packages/frontend/app/components/Skeletons/SkeletonTable/SkeletonTable.module.css, packages/frontend/app/components/Skeletons/SkeletonTable/SkeletonTable.tsx, packages/frontend/app/components/Tabs/Tabs.tsx, packages/frontend/app/components/Trade/BalancesTable/BalancesTable.tsx, packages/frontend/app/components/Trade/OpenOrdersTable/OpenOrdersTable.tsx, packages/frontend/app/components/Trade/OrderHistoryTable/OrderHistoryTable.tsx, packages/frontend/app/components/Trade/PositionsTable/PositionsTable.tsx, packages/frontend/app/routes/trade/webdataconsumer.tsx, packages/frontend/app/stores/TradeDataStore.ts, packages/frontend/app/stores/UserTradeDataStore.ts, packages/frontend/app/utils/CommonIFs.ts, packages/frontend/app/utils/Constants.ts
Skeleton Table component and No Data component have been created and adapted into;
- Balances
- Positions
- Open Orders
- Order History
Trade Data store and webdata consumer hook and components have been updated to track data loading status for associated tables.
_Other changes;
Crazy1 account has been removed from debug wallets (strobie's account is using the same address)_
=> Skeleton Table & Empty State for tables

packages/frontend/app/components/Notifications/Notifications.tsx
postNotification method has been modified to parse notification messages correctly with last changes
=> Notifications | Fix parsing after useSdk integration

packages/frontend/app/components/ShareModal/ShareModal.tsx, packages/frontend/app/components/Trade/PositionsTable/PositionsTable.module.css, packages/frontend/app/components/Trade/PositionsTable/PositionsTableRow.tsx, packages/frontend/app/routes/testpage/testpage.tsx
Change `value` attribute on Twitter post creation UI to `defaultValue` to allow user-initiated changes
=> share modal bug and styling fixes

packages/frontend/app/components/Tabs/Tabs.module.css, packages/frontend/app/components/Tabs/Tabs.tsx, packages/frontend/app/components/Trade/TradeTables/TradeTables.tsx, packages/frontend/app/routes/trade/orderbook/orderbooksection.module.css, packages/frontend/app/routes/trade/orderbook/orderbooksection.tsx
Naming has been changed on Orderbook tabs 
Wide tab option has been added into Tab component (for paddings)
Flex tab option has been added into Tab component
=> Orderbook | Naming & width fix on tabs

packages/frontend/app/components/PageHeader/PageHeader.module.css, packages/frontend/app/components/PageHeader/PageHeader.tsx, packages/frontend/app/css/app.css, packages/frontend/app/root.tsx
The element `<PageHeader />` was previously nested inside another `<header>` component. This removes the extra wrapper and preserves styling and behavior.
=> Simplify page header

packages/frontend/app/components/Notifications/Notifications.tsx
- animate the appearance/disappearance of transaction notifications
=> add notification animation

packages/frontend/app/components/BasicMenu/BasicMenu.module.css, packages/frontend/app/components/Inputs/ComboBox/ComboBox.module.css, packages/frontend/app/components/PageHeader/DepositDropdown/DepositDropdown.module.css, packages/frontend/app/components/PageHeader/DropdownMenu/DropdownMenu.module.css, packages/frontend/app/components/PageHeader/MoreDropdown/MoreDropdown.module.css, packages/frontend/app/components/PageHeader/NetworkDropdown/NetworkDropdown.module.css, packages/frontend/app/components/PageHeader/PageHeader.module.css, packages/frontend/app/components/PageHeader/RpcDropdown/RpcDropdown.module.css, packages/frontend/app/components/PageHeader/WalletDropdown/WalletDropdown.module.css, packages/frontend/app/components/Referrals/CodeTabs/CodeTabs.module.css, packages/frontend/app/components/Skeletons/SkeletonNode/SkeletonNode.module.css, packages/frontend/app/components/Trade/OrderInput/ConfirmationModal/ConfirmationModal.module.css, packages/frontend/app/components/Trade/OrderInput/MarginModal/MarginModal.module.css, packages/frontend/app/components/Trade/OrderInput/ScaleOrders/ScaleOrders.module.css, packages/frontend/app/components/Vault/VaultCard/VaultCard.module.css, packages/frontend/app/css/index.css, packages/frontend/app/routes/trade/orderbook/orderbook.module.css, packages/frontend/app/routes/trade/orderbook/orderrow/orderrow.module.css, packages/frontend/app/routes/trade/orderbook/ordertraderow/ordertraderow.module.css, packages/frontend/app/routes/trade/symbol/symbolsearch/symbollist/symbollist.module.css, packages/frontend/app/routes/trade/symbol/symbolsearch/symbolsearch.module.css, packages/frontend/app/routes/trade/watchlist/watchlistnode/watchlistnode.module.css
Introduced new CSS variables for `ease-in-out` transitions
=> Centralize transitions

packages/frontend/app/components/Trade/TradeHistoryTable/TradeHistoryTable.module.css, packages/frontend/app/components/Trade/TradeHistoryTable/TradeHistoryTable.tsx, packages/frontend/app/components/Trade/TwapTable/FillTwapTable/FillTwapTable.module.css, packages/frontend/app/components/Trade/TwapTable/FillTwapTable/FillTwapTable.tsx, packages/frontend/app/components/Trade/TwapTable/HistoryTwapTable/HistoryTwapTable.tsx, packages/frontend/app/hooks/useInfoApi.ts, packages/frontend/app/routes.ts, packages/frontend/app/routes/twapFillHistory/twapFillHistory.module.css, packages/frontend/app/routes/twapFillHistory/twapFillHistory.tsx, packages/frontend/app/routes/twapHistory/twapHistory.module.css, packages/frontend/app/routes/twapHistory/twapHistory.tsx
External Pages for TWAP Tables
- TWAP History
https://deploy-preview-180--ambi-perps.netlify.app/twapHistory/0x1cFd5AAa6893f7d91e2A0aA073EB7f634e871353
- TWAP Fill History
https://deploy-preview-180--ambi-perps.netlify.app/twapFillHistory/0x1cFd5AAa6893f7d91e2A0aA073EB7f634e871353
=> TWAP Table External Pages

packages/frontend/app/components/Pagination/GenericTablePagination.tsx, packages/frontend/app/components/Tables/GenericTable/GenericTable.module.css, packages/frontend/app/components/Tables/GenericTable/GenericTable.tsx, packages/frontend/app/components/Trade/TradeHistoryTable/TradeHistoryTable.tsx, packages/frontend/app/components/Trade/TradeHistoryTable/TradeHistoryTableHeader.tsx
- Pagination component for generic table has been created to reset page into 1 once user sorts data
- Trade History table has been adapted to Generic Table component
- Fix action btns positioning (Export as CSV btn etc..) on External Page mode
- Fix empty area issue at the end of Generic Table
=> Generic Table Add-ons

packages/frontend/app/routes/trade/orderbook/orderbook.module.css, packages/frontend/app/routes/trade/orderbook/orderbook.tsx, packages/frontend/app/routes/trade/orderbook/orderbooksection.module.css, packages/frontend/app/routes/trade/orderbook/orderbooksection.tsx
Approach has been changed into adding blank rows rather than aligning with css
With that solution we also have possibility to create a gradient effect with that blank rows by styling them according to their indexes
=> Orderbook | Vertical alignment

packages/frontend/app/routes/trade/watchlist/watchlistnode/watchlistnode.module.css, packages/frontend/app/routes/trade/watchlist/watchlistnode/watchlistnode.tsx
Static width on watchlist nodes has been removed and dynamical width calculation has been added to make values fit on watchlist divs
=> Watchlist node padding fix

packages/frontend/app/css/index.css, packages/frontend/app/routes/trade/orderbook/orderbook.module.css, packages/frontend/app/routes/trade/orderbook/orderbook.tsx, packages/frontend/app/routes/trade/orderbook/orderbooksection.module.css, packages/frontend/app/routes/trade/orderbook/orderbooksection.tsx, packages/frontend/app/routes/trade/orderbook/orderbooktrades.module.css, packages/frontend/app/routes/trade/orderbook/orderrow/orderrow.module.css
Initial count vs resize count difference fixed
Trades count fixed
Skeleton dimensions calculating dynamically
CSS variables have been used in orderbook css modules
Stacked mode fixed
=> Orderbook | Count calculation fixes

packages/frontend/app/components/Tables/GenericTable/GenericTable.module.css, packages/frontend/app/components/Tables/GenericTable/GenericTable.tsx, packages/frontend/app/components/Trade/FundingHistoryTable/FundingHistoryTable.module.css, packages/frontend/app/components/Trade/FundingHistoryTable/FundingHistoryTable.tsx, packages/frontend/app/components/Trade/FundingHistoryTable/FundingHistoryTableHeader.tsx, packages/frontend/app/components/Trade/FundingHistoryTable/FundingHistoryTableRow.tsx, packages/frontend/app/components/Trade/TradeTables/TradeTable.module.css, packages/frontend/app/components/Trade/TradeTables/TradeTables.tsx, packages/frontend/app/processors/processUserFills.ts, packages/frontend/app/routes/portfolio/portfolio.tsx, packages/frontend/app/routes/trade/webdataconsumer.tsx, packages/frontend/app/stores/UserTradeDataStore.ts, packages/frontend/app/utils/Constants.ts, packages/frontend/app/utils/UserDataIFs.ts, packages/sdk/src/utils/types.ts
Funding History table and generic table fixes
- Funding history data fetch through ws
- Rendering data on table
- Generic table adaption into Funding history table
- Sorting fix on generic table (re-render issue)
- Positioning fix on action buttons (portfolio page)
_View all page will be added by tomorrow_
=> Funding History Table

packages/frontend/app/css/index.css, packages/frontend/app/hooks/useInfoApi.ts, packages/frontend/app/processors/processUserFills.ts, packages/frontend/app/routes.ts, packages/frontend/app/routes/fundingHistory/fundingHistory.module.css, packages/frontend/app/routes/fundingHistory/fundingHistory.tsx, packages/frontend/app/utils/UserDataIFs.ts
Info api method has been created to fetch funding history data of user.
External page has been created and route rule has been defined.
`..../fundingHistory/:userAddress` route can be used for checking
=> Funding History Page

packages/frontend/app/components/Tables/GenericTable/GenericTable.tsx, packages/frontend/app/processors/processUserFills.ts
Shadow effect has been disabled for page mode and small amount of data cases
=> Generic Table | Fix redundant shadow effects

packages/frontend/app/components/Trade/OpenOrdersTable/OpenOrdersTable.tsx, packages/frontend/app/components/Trade/OpenOrdersTable/OpenOrdersTableHeader.tsx, packages/frontend/app/utils/orderbook/OrderBookIFs.ts
Updated OpenOrdersTable.tsx, OpenOrderTableHeader.tsx, OrderBookIF.tsx files to add default sorting to Open Orders table.
=> Default sorting functionality of open orders

packages/frontend/app/components/Tables/GenericTable/GenericTable.module.css, packages/frontend/app/components/Tables/GenericTable/GenericTable.tsx, packages/frontend/app/components/Trade/TradeTables/TradeTable.module.css, packages/frontend/app/css/index.css, packages/frontend/app/routes/trade.module.css
Min height has been defined for tables `--trade-tables-min-height-desktop` and used in grid layout.
Also resize event listener has been added to change shadow effect on tables if needed
=> Table min height

packages/frontend/app/components/LoadingIndicator/LoadingIndicator.module.css, packages/frontend/app/components/ShareModal/ShareModal.module.css, packages/frontend/app/components/Trade/OpenOrdersTable/OpenOrdersTable.module.css, packages/frontend/app/components/Trade/OpenOrdersTable/OpenOrdersTableRow.tsx, packages/frontend/app/components/Trade/OrderHistoryTable/OrderHistoryTable.module.css, packages/frontend/app/components/Trade/OrderHistoryTable/OrderHistoryTableRow.tsx, packages/frontend/app/components/Trade/OrderInput/LeverageSlider/LeverageSlider.tsx, packages/frontend/app/components/Trade/OrderInput/ReduceAndProfitToggle/ReduceAndProfitToggle.module.css, packages/frontend/app/components/Trade/OrderInput/ReduceAndProfitToggle/ReduceAndProfitToggle.tsx, packages/frontend/app/components/Trade/PositionsTable/PositionsTable.module.css, packages/frontend/app/components/Trade/PositionsTable/PositionsTable.tsx, packages/frontend/app/components/Trade/PositionsTable/PositionsTableRow.tsx, packages/frontend/app/components/Trade/TakeProfitsModal/TakeProfitsModal.module.css, packages/frontend/app/components/Trade/TakeProfitsModal/TakeProfitsModal.tsx, packages/frontend/app/components/Trade/ToggleSwitch/ToggleSwitch.tsx
=> Add Tpsl to order input

packages/frontend/app/components/Tables/GenericTable/GenericTable.tsx
Dynamic row count has been added into generic table to show more than given row count (`slicedLimit` prop) when component have more space than estimated
2px offset has been added to shadow effect checker method to handle edge cases on shadow effect
=> Generic Table | Dynamic Row Count

packages/frontend/app/routes/trade/orderbook/orderbook.tsx
- JSON.stringify usages have been removed from useEffects
- Timeout on selectedResolutionRef assignemnt has been removed 
- RowLock timeout has been moved out of callback method to keep ref to clear out before creating the new one
=> Orderbook | Memory fixes

packages/frontend/app/components/Tables/GenericTable/GenericTable.module.css, packages/frontend/app/components/Tables/GenericTable/GenericTable.tsx, packages/frontend/app/css/index.css, packages/frontend/app/hooks/workers/webdata2.worker.ts
- Triggering shadow checker once user has been changed has been fixed
- Sort type change listeners has been handled for user change event
- Removed mock active twap data from app
- Z-index has been added to fix action bar correctly on Positions table
=> Generic Table | Fixes

packages/frontend/app/routes/trade/symbol/symbolsearch/symbollist/symbollist.tsx, packages/frontend/app/routes/trade/watchlist/watchlist.module.css, packages/frontend/app/routes/trade/watchlist/watchlist.tsx, packages/frontend/app/routes/trade/watchlist/watchlistnode/watchlistnode.module.css, packages/frontend/app/stores/TradeDataStore.ts
- updated hover effect for watchlist items to increase highlighted and clickable area
- added click handler for heart icon in watchlist
- show empty heart when active market is not yet favorited
- show most recently favorited markets on left side of watchlist
=> update hover effect for watchlist nodes

packages/frontend/app/components/Trade/TradeTables/TradeTables.tsx, packages/frontend/app/components/Trade/VaultDepositorsTable/VaultDepositorsTable.module.css, packages/frontend/app/components/Trade/VaultDepositorsTable/VaultDepositorsTable.tsx, packages/frontend/app/components/Trade/VaultDepositorsTable/VaultDepositorsTableHeader.tsx, packages/frontend/app/components/Trade/VaultDepositorsTable/VaultDepositorsTableRow.tsx, packages/frontend/app/routes/vaults/vaultDetails.tsx, packages/frontend/app/utils/Utils.ts, packages/frontend/app/utils/VaultIFs.ts
- Depositors table has been added into Vault Details page
- Showing all depositors with scrolling
- Handling tab & page changes
=> Vault Depositors Table

packages/frontend/app/components/Leaderboard/LeaderboardTable/LeaderboardTable.module.css, packages/frontend/app/components/Referrals/CodeTabs/CodeTabs.module.css, packages/frontend/app/components/Referrals/CodeTabs/CodeTabs.tsx, packages/frontend/app/routes/trade/symbol/symbolsearch/symbolsearch.tsx
finish all minor changes for frontend review, colors, borders, etc...
=> Last frontend reviews

packages/frontend/app/routes/trade/orderbook/orderbooksection.tsx
* Fixed a sizing issue causing a line in the order book to appear discontinuous
* Fixed linter errors in `orderbooksection.tsx` file
=> Fix order book line

packages/frontend/app/components/Trade/TradeTables/TradeTables.tsx, packages/sdk/src/info.ts, packages/sdk/src/ws.ts
Multiple callback support has been added into ws sdk to manage subscription related problem into 'userFills' channel
=> Trade History Table | Fix loader issue

packages/frontend/app/components/NoConnectionIndicator/NoConnectionIndicator.tsx, packages/frontend/app/components/Skeletons/ChartSkeleton/ChartSkeleton.tsx, packages/frontend/app/components/Tables/GenericTable/GenericTable.tsx, packages/frontend/app/components/Trade/BalancesTable/BalancesTable.tsx, packages/frontend/app/components/Trade/TwapTable/FillTwapTable/FillTwapTable.tsx, packages/frontend/app/components/WsReconnectingIndicator/WsReconnectingIndicator.tsx, packages/frontend/app/hooks/useInfoApi.ts, packages/frontend/app/hooks/workers/webdata2.worker.ts, packages/frontend/app/processors/processSymbolInfo.ts, packages/frontend/app/processors/processUserBalance.ts, packages/frontend/app/processors/processUserFills.ts, packages/frontend/app/routes/trade/symbol/symbolsearch/symbolsearch.tsx, packages/frontend/app/routes/vaults/vaultCard.tsx, packages/frontend/app/utils/SymbolInfoIFs.ts, packages/frontend/app/utils/UserDataIFs.ts
Fixes for some of lint errors on;
- GenericTable
- NoConnectionIndicator
- ChartSkeleton
- WsReconnectIndicator
- SymbolSearch
- VaultCard
- ProcessUserBalance
- FillTwapTable
- ProcessUserFills
- ProcessSymbolInfo
=> Fix Lint Errors

packages/frontend/app/contexts/TradingviewContext.tsx, packages/frontend/app/routes/chart/data/utils/utils.ts
Using temporary SVG icon, will be changed later according to Figma design
=> added liquidations button on chart header widget

packages/frontend/app/utils/orderbook/OrderBookIFs.ts, packages/frontend/app/utils/orderbook/OrderBookUtils.ts
Updated OrderBookIF.ts, OrderBookUtils.ts to fix broken sorting of price and TP/SL fields in order history
=> Fix broken sorting of price and TP/SL fields in order history.

packages/frontend/app/routes/chart/chart.tsx, packages/frontend/app/routes/trade.module.css, packages/frontend/app/routes/trade.tsx, packages/frontend/app/stores/AppStateStore.ts
Toggle feature for debug toolbar has been added which will triggered with Alt+D / Option+D key combinations
=> DebugToolbar | Toggle toolbar with Alt+D / Option+D

packages/frontend/app/components/PageHeader/DropdownMenu/DropdownMenu.tsx, packages/frontend/app/components/PageHeader/PageHeader.tsx, packages/frontend/app/components/Trade/OrderInput/OrderInput.tsx, packages/frontend/app/components/Trade/TradeTables/TradeTables.tsx, packages/frontend/app/routes/trade/symbol/symbolsearch/symbolsearch.module.css, packages/frontend/app/routes/trade/symbol/symbolsearch/symbolsearch.tsx
=> finish up general kill list

packages/frontend/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
=> Upgrade @fogo/sessions-sdk-react to 0.0.9

packages/frontend/app/components/WsConnectionChecker/WsConnectionChecker.tsx, packages/frontend/app/hooks/usePage.ts
Hiding reconnect indicator on Landing Page
=> Websocket | Hide reconnect indicator on Landing Page

packages/frontend/app/components/Trade/OrderInput/ConfirmationModal/ConfirmationModal.tsx
Action and Size label colors have been assigned from selected color mode
=> Confirm Modal | Assign value label colors from selected color mode

packages/frontend/app/components/Trade/OrderInput/ConfirmationModal/ConfirmationModal.tsx, packages/frontend/app/components/Trade/OrderInput/OrderInput.tsx, packages/frontend/app/hooks/useDepositService.ts, packages/frontend/app/hooks/useMarketOrderService.ts, packages/frontend/app/hooks/useWithdrawService.ts, packages/frontend/app/routes/portfolio/usePortfolioManager.ts, packages/frontend/app/routes/portfolio/usePortfolioModals.tsx, packages/frontend/app/services/marketOrderService.ts, packages/frontend/package.json, pnpm-lock.yaml
Deposit and withdraw modals' "Available to Deposit/Withdraw" fields now update every 2 seconds or whenever the modal is opened.
=> Deposit and Withdraw Modals update available fields

packages/frontend/app/components/Trade/OrderInput/OrderInput.tsx, packages/frontend/app/hooks/useMarketOrderService.ts, packages/frontend/app/services/marketOrderService.ts
This sends buy and sell market transactions to the chain
=> Enable buy and sell market orders

packages/frontend/app/components/Trade/OrderInput/OrderInput.tsx
Removed redundant useEffect dependency to fix value changing issue once format type has been changed
=> Size Input | Fix numformat change issue

packages/frontend/app/components/ShareModal/ShareModal.module.css, packages/frontend/app/components/ShareModal/ShareModal.tsx
* hide Referral Code fields
* hide extraneous buttons
* adjust whitespace
=> hide non-MVP features in `ShareModal.tsx` file

packages/frontend/app/components/PageHeader/PageHeader.tsx
- removed the intermediary deposit/withdraw modal when Deposit is clicked from the page header
=> remove intermediary deposit dropdown from page header

packages/frontend/app/routes/trade/webdataconsumer.tsx
Removed redundant length check, also address checkers have been fixed
=> OrderHistoryTable | Fix loader issue

packages/frontend/app/routes/trade/webdataconsumer.tsx
Reset for webdataconsumer refs has been added
=> Balances Table | Reset issue

packages/frontend/app/components/Trade/LeverageSliderModal/LeverageSliderModal.tsx, packages/frontend/app/components/Trade/OrderInput/LeverageSlider/LeverageSlider.module.css, packages/frontend/app/components/Trade/OrderInput/LeverageSlider/LeverageSlider.tsx, packages/frontend/app/components/Trade/PositionsTable/PositionsTableRow.tsx
To toggle the leverage banner on the coin, refer to code on line 163-175 in PositionsTableRow.tsx
=> style position sizes in table

packages/frontend/app/components/Trade/TradeTables/TradeTables.tsx, packages/frontend/app/contexts/TradingviewContext.tsx, packages/frontend/app/routes/chart/data/customDataFeed.ts, packages/frontend/app/stores/TradeDataStore.ts, packages/sdk/src/websocket-instance.ts
Multicallback support has been added back after multi ws instance implementation, to fix for loading state problems on TradeHistory
For the positions table required boolen value has been assigned to fix loading issue
=> Websocket | Handling multi-callbacks

packages/frontend/app/components/Inputs/NumFormattedInput/NumFormattedInput.tsx, packages/frontend/app/components/Portfolio/PortfolioDeposit/PortfolioDeposit.tsx, packages/frontend/app/components/Portfolio/PortfolioWithdraw/PortfolioWithdraw.tsx, packages/frontend/app/hooks/useNumFormatter.ts, packages/frontend/app/routes/testpage/testpage.tsx
- prevent minimum size warning from appearing while typing valid deposit amount (i.e 10)
- submit deposit/withdraw on enter keypress
- allow $ prefix for deposit/withdraw input
=> improve usability of deposit & withdraw modals

packages/frontend/app/components/Trade/OrderInput/OrderInput.tsx, packages/frontend/app/components/Trade/OrderInput/PriceInput/PriceInput.module.css, packages/frontend/app/components/Trade/OrderInput/PriceInput/PriceInput.tsx
- add isMidModeActive to automatically sync the latest mid price with the user's limit price input
=> add mode for automatically updating limit price to mid price

packages/frontend/app/components/Trade/OrderInput/OrderInput.tsx, packages/frontend/app/components/Trade/PositionsTable/PositionsTableRow.tsx, packages/frontend/app/hooks/useSdk.tsx, packages/frontend/app/processors/processUserFills.ts, packages/frontend/app/routes/trade/webdataconsumer.tsx, packages/frontend/app/services/marketOrderService.ts, packages/frontend/app/utils/Constants.ts, packages/frontend/app/utils/UserDataIFs.ts, packages/frontend/package.json
When limit orders are created then filled 5-10 seconds later by the keeper, the fill event was not getting passed to the user tables at all. It was observed in the network tab, but it didn't trigger any events in the react plumbing or show up in the table.
This was determined to be because the SDK was going into sleep mode nearly every second (see timing on logs below). And when that happened, even though the web socket connection/subscription remained open, subscription events were not processed. I don't understand the sleep system as well, so my change in here was: 
1) take out the user subscriptions from the stashed subscription system. I think this is fine since compared to order book these are light weight, and you really don't want to miss an order or fill when you come back from an …
=> Missing limit fills events

packages/frontend/app/processors/processOrderBook.ts, packages/sdk/src/utils/types.ts
Added 'S' into side types in OrderBook to indicate if user has sell side order on OrderBook
=> OrderBook | Mark Users' sell orders in OrderBook

packages/frontend/app/routes/chart/orders/component/LabelComponent.ts, packages/frontend/app/services/limitOrderService.ts, packages/frontend/app/services/marketOrderService.ts, packages/frontend/package.json, pnpm-lock.yaml
* SDK transaction changes to speed up
* Atomic drag of limit lines
* Set user leverage transaction (to be wired)
* Limit order close modal
=> Sdk change

packages/frontend/app/components/Tables/GenericTable/GenericTable.module.css, packages/frontend/app/components/Tables/GenericTable/GenericTable.tsx
Trade tables have been modified to show all data on tables, native scroll has been added
=> Trade Tables | Show All - Native Scroll

packages/frontend/app/components/Trade/LeverageSliderModal/LeverageSliderModal.tsx, packages/frontend/app/components/Trade/OrderInput/LeverageSlider/LeverageSlider.tsx, packages/frontend/app/components/Trade/OrderInput/OrderInput.tsx, packages/frontend/app/components/Trade/OrderInput/SizeInput/SizeInput.tsx, packages/frontend/app/components/Trade/PositionsTable/PositionsTableRow.tsx, packages/frontend/package.json
- initialize leverage slider to current open position leverage on first load
- fix selection of order input component on alpha character keypress
=> Release 0.1.6

packages/frontend/app/components/Tables/GenericTable/GenericTable.tsx
Table header alignment fixed for scroll case on trade tables
=> Trade Tables | Fix table header alignment 

packages/frontend/app/routes/chart/orders/component/LineComponent.ts
Probably test flow;
1. Open first deploy site
2. Connect wallet
3. Drag Limit Order
=> fix: limit line not updating when dragging limit label

packages/frontend/app/routes/trade/webdataconsumer.tsx, packages/frontend/app/utils/UserDataIFs.ts
Adding notifications once a user's order has been filled
=> Notifications | User Fills

packages/frontend/app/components/PageHeader/DepositDropdown/DepositDropdown.tsx, packages/frontend/app/components/Trade/OrderInput/OrderInput.module.css, packages/frontend/app/components/Trade/OrderInput/OrderInput.tsx, packages/frontend/app/hooks/useUnifiedMarginData.ts, packages/frontend/package.json
- clear margin bucket on logout to reset available to trade
- round dust balance to zero
- fix enter key handling when submit button disabled
- update disabled submit button text to advise deposit
=> Bug fixes aug 8

packages/frontend/app/components/Trade/OrderInput/OrderInput.tsx, packages/frontend/package.json
- set max mode to true if the user's update to leverage would require 100% or more of their collateral
=> Release 0.1.16

packages/frontend/app/routes/chart/orders/useOpenOrderLines.ts
Updated quantityTextValue calculation to use logical OR, ensuring 0 values also fall back to the next available value
=> Replace ?? with || in quantityTextValue

packages/frontend/app/components/PageHeader/DepositDropdown/DepositDropdown.tsx, packages/frontend/app/components/PageHeader/PageHeader.tsx, packages/frontend/app/components/Tables/GenericTable/GenericTable.tsx, packages/frontend/app/root.tsx, packages/frontend/package.json
- added custom properties to track login button clicks by location in the app
=> Release 0.1.20 3

packages/frontend/app/components/PageHeader/PageHeader.tsx, packages/frontend/package.json
- added tracking of successful logins and logouts
=> Release 0.1.20 6

packages/frontend/app/utils/functions/getDurationSegment.ts, packages/frontend/package.json
- add more granular duration segments
=> release 0.1.21-8

packages/frontend/app/components/Inputs/ComboBox/ComboBox.module.css, packages/frontend/app/components/Inputs/ComboBox/ComboBoxContainer.tsx, packages/frontend/app/components/PageHeader/PageHeader.tsx, packages/frontend/app/components/Portfolio/PortfolioDeposit/PortfolioDeposit.tsx, packages/frontend/app/components/Portfolio/PortfolioWithdraw/PortfolioWithdraw.tsx, packages/frontend/app/components/Trade/LimitCloseModal/LimitCloseModal.tsx, packages/frontend/app/components/Trade/MarketCloseModal/MarketCloseModal.tsx, packages/frontend/app/routes/chart/orders/component/LabelComponent.ts, packages/frontend/app/routes/trade.module.css, packages/frontend/app/utils/functions/getDurationSegment.ts, packages/frontend/package.json
- fixed layout bugs when order book in large mode
- added additional transaction failure tracking
- updated time durations segments to track values under 10s with more granularity
=> Release 0.1.22

packages/frontend/app/components/Inputs/ComboBox/ComboBoxContainer.tsx, packages/frontend/app/components/Trade/OrderInput/LeverageSlider/LeverageSlider.module.css, packages/frontend/app/components/Trade/OrderInput/LeverageSlider/SliderTrack.tsx, packages/frontend/app/components/Trade/OrderInput/OrderInput.tsx, packages/frontend/app/stores/DebugStore.ts
=> Pin minimum label to track start if leverage < 3x

packages/frontend/app/hooks/useUnifiedMarginData.tsx, packages/frontend/app/root.tsx
Converting useUnifiedMarginData hook to context to fix multiple render issues which triggered on tables etc.
=> UnifiedMarginData Context

packages/frontend/app/components/Portfolio/PortfolioDeposit/PortfolioDeposit.tsx, packages/frontend/app/components/Portfolio/PortfolioWithdraw/PortfolioWithdraw.tsx, packages/frontend/app/components/Trade/LimitCloseModal/LimitCloseModal.tsx, packages/frontend/app/components/Trade/MarketCloseModal/MarketCloseModal.tsx, packages/frontend/app/components/Trade/OpenOrdersTable/OpenOrdersTableRow.tsx, packages/frontend/app/components/Trade/OrderInput/OrderInput.tsx, packages/frontend/app/components/Trade/PositionsTable/PositionsTableRow.tsx, packages/frontend/app/routes/chart/orders/component/LabelComponent.ts, packages/frontend/package.json
- add explorerLink tracking property
=> release 0.1.25-1

packages/frontend/app/components/PageHeader/PageHeader.tsx, packages/frontend/package.json
- remove landing event tracking
=> release 0.1.25-3

packages/frontend/app/assets/tokens/index.ts, packages/frontend/app/components/Inputs/ComboBox/ComboBoxContainer.tsx, packages/frontend/app/contexts/MarketDataContext.tsx, packages/frontend/app/hooks/useInfoApi.ts, packages/frontend/app/hooks/useRestPoller.ts, packages/frontend/app/hooks/workers/orderbook.worker.ts, packages/frontend/app/processors/processSymbolInfo.ts, packages/frontend/app/root.tsx, packages/frontend/app/routes/chart/data/customDataFeed.ts, packages/frontend/app/routes/chart/data/fetchCandleData.ts, packages/frontend/app/routes/trade/orderbook/orderbook.tsx, packages/frontend/app/routes/trade/orderbook/orderbooktrades.tsx, packages/frontend/app/routes/trade/symbol/symbolsearch/symbolsearch.module.css, packages/frontend/app/routes/trade/symbol/symbolsearch/symbolsearch.tsx, packages/frontend/app/routes/trade/traderoutehandler.tsx, packages/frontend/app/routes/trade/webdataconsumer.tsx, packages/frontend/app/utils/Constants.ts, packages/frontend/package.json, packages/sdk/src/config.ts, packages/sdk/src/info.ts, packages/sdk/src/utils/types.ts, packages/sdk/src/websocket-instance.ts, packages/sdk/src/websocket-pool.ts
RestPoller hook has been added to use in OrderBook component. 
OrderBook component and worker file have been adapted to polling implementation.
=> OrderBook | Fetching data by polling

packages/frontend/app/routes/trade/orderbook/orderbooksection.tsx
Fill orderbook on mobile devices by fixing ordercount calculation method
=> OrderBook | Fix ordercount for mobile

packages/frontend/app/components/Trade/OrderInput/PriceInput/PriceInput.tsx, packages/frontend/app/css/index.css, packages/frontend/app/routes/trade.tsx, packages/frontend/app/routes/trade/orderbook/orderbook.tsx, packages/frontend/app/routes/trade/orderbook/orderbooksection.tsx, packages/frontend/app/routes/trade/orderbook/orderrow/orderrow.tsx
Row click listener has been added for mobile to switch Order tab and pulse animation on price input
=> OrderBook | OrderRow mobile click

packages/frontend/app/contexts/TradingviewContext.tsx, packages/frontend/app/routes/trade/orderbook/orderbook.tsx, packages/frontend/package.json
- added chart resolution tracking
=> Release 0.2.4

packages/frontend/app/components/FeedbackModal/FeedbackModal.module.css, packages/frontend/app/components/FeedbackModal/FeedbackModal.tsx, packages/frontend/app/components/PageHeader/DepositDropdown/DepositDropdown.tsx, packages/frontend/app/components/PageHeader/DropdownMenu/DropdownMenu.tsx, packages/frontend/app/components/PageHeader/PageHeader.tsx, packages/frontend/app/css/index.css
- added a feedback modal that can be opened from the three-dot menu in the page header
=> Add feedback modal

packages/frontend/app/routes/trade/orderbook/orderbook.tsx
Assign spread text with lowest difference between buys & sells always
=> Orderbook | Spread text with lowest diff

packages/frontend/app/components/AppOptions/AppOptions.tsx, packages/frontend/app/routes/chart/orders/OrderLines.tsx, packages/frontend/app/routes/chart/orders/component/LineComponent.ts, packages/frontend/app/stores/AppSettingsStore.ts
Fixes :
**- black screen occur when click apply defaults**
1. Open Settings
2. Click "Apply Default" Button
3. Get Black Screen and cannot access Settings modal again
**- order lines duplicated when changing resolution**
1. Open chart (it should have order lines)
2. Switch other resolution(period)
3. Try dragging any order line
4. See the same line appear again without a label
=> Tw chart internationalize perps
